services:
  elite-tracker-bot:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER_GUILD_ID: ${OWNER_GUILD_ID}
    volumes:
      - elite-data:/data

volumes:
  elite-data:
